spring:
  profiles:
    active: dev
  application:
    name: minaShop
    admin:
      enabled: true
  jpa:
    database: MYSQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect:
          storage_engine: innodb
  datasource:
    one:
      platform: MYSQL
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
      username: root
      password: Root
      driver-class-name: com.mysql.cj.jdbc.Driver
    two:
       platform: MYSQL
       url: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
       username: root
       password: Root
       driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
  redis:
    port: 32102
    host: localhost
LOG_DATEFORMAT_PATTERN: yyyy/MM/dd HH:mm:ss:sss
server:
  port: 9999
  servlet:
    context-path: /mina
logging:
  level:
    org:  info
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN}}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(${PID:-}){magenta} %clr{faint} %clr([%t]){faint} %clr([%-40.40logger{39} %L]){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"

acme:
  remote-address: 192.168.1.1
  security:
    username: admin
    roles:
      - USER
      - ADMIN
